namespace EEMod.Localization
{
    //public static class InteritosLocalization
    //{
    // https://github.com/tModLoader/tModLoader/blob/35d0e8b0f7cfb34df8c0451d80e96ba35c0b50a6/ExampleMod/Localization/en-US.lang#L7
    // The following are the currently autogenerated keys: ItemName, ItemTooltip, BuffName, BuffDescription, ProjectileName, NPCName, MapObject, and Prefix
    // ae
    // NPCName.name
    // ProjectileName.name
    // ItemName.name
    // ItemTooltip.name
    // BuffName.name
    // BuffDescription.name
    //
    /* public static string GetText(string value)
    {
        return Language.GetText(value);
    }

    public static string GetNPCName(string npcname) => GetText("NPCName." + npcname);
    public static string GetProjectileName(string projname) => GetText("ProjectileName."+projname);
    public static string GetItemName(string itemname) => GetText("ItemName." + itemname);
    public static string GetItemTooltip(string itemname) => GetText("ItemTooltip." + itemname);
    public static string GetBuffName(string buffname) => GetText("BuffName." + buffname);
    public static string GetBuffDesc(string buffname) => GetText("BuffDescription" + buffname); */
    //}
}

//      // private static string[][] _localizations;
//      class TranslationThing : ConcurrentDictionary<GameCulture, ConcurrentDictionary<string, string>>
//      {
//          public List<ModTranslation> GetTranslations(Mod mod)
//          {
//              List<ModTranslation> modtranslations = new List<ModTranslation>();
//              foreach (var s in this)
//              {
//                  foreach (var d in s.Value)
//                  {
//                      if (d.Key == null || d.Value == null)
//                          continue;
//                      ModTranslation modtransl = mod.CreateTranslation(d.Key);
//                      modtransl.AddTranslation(s.Key, d.Value);
//                      modtranslations.Add(modtransl);
//                  }
//              }
//              return modtranslations;
//          }
//          public IEnumerable<ModTranslation> GetTranslationsYield(Mod mod)
//          {
//              foreach (var s in this)
//              {
//                  foreach (var d in s.Value)
//                  {
//                      if (d.Key == null || d.Value == null)
//                          continue;
//                      ModTranslation modtransl = mod.CreateTranslation(d.Key);
//                      modtransl.AddTranslation(s.Key, d.Value);
//                      yield return modtransl;
//                  }
//              }
//          }
//      }

//      public static void Load()
//{
//	//_localizations = new[]
//	//{
//	//	new [] { "StagrelDeathText", "Forgotten creatures are empowered by the Oasis" }
//	//};
//}
//public static void Unload()
//{
//	// _localizations = null;
//}

//public static void AddLocalizations()
//{
//	Load();
//	//foreach (string[] localization in _localizations)
//	//{
//	//	ModTranslation text = ModContent.GetInstance<EEMod>().CreateTranslation(localization[0]);
//	//	text.SetDefault(localization[1]);
//	//	ModContent.GetInstance<EEMod>().AddTranslation(text);
//	//}
//	Unload();
//}