using System.IO;
using System.Text;
using Hjson;
using Microsoft.CodeAnalysis;
using Newtonsoft.Json;

namespace EndlessEscapade.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class AmbienceSoundGenerator : IIncrementalGenerator
{
    private const string ToolVersion = "0.1";

    /// <summary>
    ///     The file extension associated with this generator.
    /// </summary>
    public const string Extension = ".eesound";

    public void Initialize(IncrementalGeneratorInitializationContext initializationContext) {
        var files = initializationContext.AdditionalTextsProvider.Where(file => file.Path.EndsWith(Extension));

        var contents = files.Select(
            static (text, token) => {
                var content = text.GetText(token);

                var json = HjsonValue.Parse(content.ToString()).ToString(Stringify.Plain);
                var data = JsonConvert.DeserializeObject<AmbienceSoundData>(json);

                return (
                    Name: Path.GetFileNameWithoutExtension(text.Path),
                    Data: data
                );
            }
        );

        initializationContext.RegisterSourceOutput(
            contents,
            static (sourceContext, content) => {
                sourceContext.AddSource($"{content.Name}.g.cs", GenerateAmbienceSound(content.Name, content.Data));
            }
        );
    }

    private static string GenerateAmbienceSound(string name, AmbienceSoundData data) {
        return $@" // <auto-generated/>

using Terraria.Audio;
using ReLogic.Utilities;

namespace EndlessEscapade.Common.Ambience;

[System.CodeDom.Compiler.GeneratedCodeAttribute(""EndlessEscapade.Generators.AmbienceSoundGenerator"", ""{ToolVersion}"")]
public sealed class {name} : IAmbienceSound
{{
	public SoundStyle Sound {{ get; }} = new(""{data.SoundPath}"", {data.Variants}, SoundType.Ambient) {{
		Volume = 0.8f
	}};

    public int Chance {{ get; }} = {data.Chance};

    public string[] Signals {{ get; }} = {data.Signals.ToStringArray()};

    public SlotId Slot {{ get; set; }}
}}";
    }
}
