name: Lint

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore .NET dependencies
      run: dotnet restore

    - name: Lint
      run: dotnet format style EndlessEscapade.sln --verify-no-changes
